// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_0mxUZj9x6BskfP6t3K2GgNej_BMULI',
    appId: '1:402322696505:web:088415aebdee77ba26e0e8',
    messagingSenderId: '402322696505',
    projectId: 'firestore-f8329',
    authDomain: 'firestore-f8329.firebaseapp.com',
    storageBucket: 'firestore-f8329.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeqVcC3MOE9n0QwWoj7jdu1lFgRtztY34',
    appId: '1:402322696505:android:f171fdf3057fcc7926e0e8',
    messagingSenderId: '402322696505',
    projectId: 'firestore-f8329',
    storageBucket: 'firestore-f8329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvNyEjlu8Lan3iKQVE_rKzBmzGC1OqgI0',
    appId: '1:402322696505:ios:f1f6f81b6a16a80026e0e8',
    messagingSenderId: '402322696505',
    projectId: 'firestore-f8329',
    storageBucket: 'firestore-f8329.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvNyEjlu8Lan3iKQVE_rKzBmzGC1OqgI0',
    appId: '1:402322696505:ios:f1f6f81b6a16a80026e0e8',
    messagingSenderId: '402322696505',
    projectId: 'firestore-f8329',
    storageBucket: 'firestore-f8329.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7_0mxUZj9x6BskfP6t3K2GgNej_BMULI',
    appId: '1:402322696505:web:088415aebdee77ba26e0e8',
    messagingSenderId: '402322696505',
    projectId: 'firestore-f8329',
    authDomain: 'firestore-f8329.firebaseapp.com',
    storageBucket: 'firestore-f8329.appspot.com',
  );

}